In [16]:
import copy
import torch

x = torch.tensor([1,2,3.]).requires_grad_()
x_clone = x.clone()
x_deep_copy = copy.deepcopy(x)
y = x.contiguous()

#z = torch.mean(torch.mul(y, -1))
#z.backward()
print(z)
print(f'x = {x}')
print(f'x_clone = {x_clone}')
print(f'x_deep_copy = {x_deep_copy}')
print(y)

tensor(-2., grad_fn=<MeanBackward0>)
x = tensor([1., 2., 3.], requires_grad=True)
x_clone = tensor([1., 2., 3.], grad_fn=<CloneBackward0>)
x_deep_copy = tensor([1., 2., 3.], requires_grad=True)
tensor([1., 2., 3.], requires_grad=True)


In [17]:
print(z.requires_grad)

True


In [18]:
print(x.grad)
print(x_clone.grad)
print(x_deep_copy.grad)
print(y.grad)

None
None
None
None


/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:1104: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten/src/ATen/core/TensorBody.h:475.)
  return self._grad


In [19]:
x2 = y[1:3] * y[2:4]
x2 = torch.mean(x2)
x2.backward()

In [20]:
print(x.grad)
print(x_clone.grad)
print(x_deep_copy.grad)
print(y.grad)

tensor([0.0000, 1.5000, 4.0000])
None
None
tensor([0.0000, 1.5000, 4.0000])


/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:1104: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten/src/ATen/core/TensorBody.h:475.)
  return self._grad
